name: finki-recordings-listing

services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/finki-hub/finki-recordings-listing:local
    ports:
      - "8080:80"
    restart: unless-stopped
